# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'greenscreen.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(342, 185)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBoxDelay = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxDelay.setObjectName("spinBoxDelay")
        self.gridLayout_3.addWidget(self.spinBoxDelay, 0, 1, 1, 1)
        self.pushButtonReset = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonReset.sizePolicy().hasHeightForWidth())
        self.pushButtonReset.setSizePolicy(sizePolicy)
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.gridLayout_3.addWidget(self.pushButtonReset, 0, 0, 1, 1)
        self.checkBoxGreenScreen = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxGreenScreen.setObjectName("checkBoxGreenScreen")
        self.gridLayout_3.addWidget(self.checkBoxGreenScreen, 0, 2, 1, 2)
        self.spinBoxCam = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxCam.setMaximum(255)
        self.spinBoxCam.setProperty("value", 0)
        self.spinBoxCam.setObjectName("spinBoxCam")
        self.gridLayout_3.addWidget(self.spinBoxCam, 0, 4, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxNoise = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxNoise.setObjectName("comboBoxNoise")
        self.comboBoxNoise.addItem("")
        self.comboBoxNoise.addItem("")
        self.comboBoxNoise.addItem("")
        self.gridLayout.addWidget(self.comboBoxNoise, 1, 0, 1, 1)
        self.labelSize = QtWidgets.QLabel(self.groupBox)
        self.labelSize.setObjectName("labelSize")
        self.gridLayout.addWidget(self.labelSize, 1, 2, 1, 1)
        self.horizontalSliderNoiseSize = QtWidgets.QSlider(self.groupBox)
        self.horizontalSliderNoiseSize.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalSliderNoiseSize.setMinimum(1)
        self.horizontalSliderNoiseSize.setMaximum(100)
        self.horizontalSliderNoiseSize.setProperty("value", 30)
        self.horizontalSliderNoiseSize.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderNoiseSize.setInvertedAppearance(False)
        self.horizontalSliderNoiseSize.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSliderNoiseSize.setTickInterval(10)
        self.horizontalSliderNoiseSize.setObjectName("horizontalSliderNoiseSize")
        self.gridLayout.addWidget(self.horizontalSliderNoiseSize, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalSliderThresh = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSliderThresh.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalSliderThresh.setMaximum(100)
        self.horizontalSliderThresh.setProperty("value", 30)
        self.horizontalSliderThresh.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderThresh.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSliderThresh.setObjectName("horizontalSliderThresh")
        self.gridLayout_4.addWidget(self.horizontalSliderThresh, 0, 1, 1, 1)
        self.labelThresh = QtWidgets.QLabel(self.groupBox_3)
        self.labelThresh.setObjectName("labelThresh")
        self.gridLayout_4.addWidget(self.labelThresh, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 2, 1, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBoxRed = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxRed.setMaximum(255)
        self.spinBoxRed.setProperty("value", 0)
        self.spinBoxRed.setObjectName("spinBoxRed")
        self.gridLayout_2.addWidget(self.spinBoxRed, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.spinBoxGreen = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxGreen.setMaximum(255)
        self.spinBoxGreen.setProperty("value", 255)
        self.spinBoxGreen.setObjectName("spinBoxGreen")
        self.gridLayout_2.addWidget(self.spinBoxGreen, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.spinBoxBlue = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxBlue.setMaximum(255)
        self.spinBoxBlue.setProperty("value", 0)
        self.spinBoxBlue.setObjectName("spinBoxBlue")
        self.gridLayout_2.addWidget(self.spinBoxBlue, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.horizontalSliderThresh.valueChanged['int'].connect(self.labelThresh.setNum)
        self.horizontalSliderNoiseSize.valueChanged['int'].connect(self.labelSize.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Greenscreen"))
        self.spinBoxDelay.setToolTip(_translate("MainWindow", "<html><head/><body><p>Amount of seconds to wait before reseting camera frame.</p><p>Note: window may freeze</p></body></html>"))
        self.pushButtonReset.setToolTip(_translate("MainWindow", "Capture a new frame for reference."))
        self.pushButtonReset.setText(_translate("MainWindow", "Reset"))
        self.checkBoxGreenScreen.setText(_translate("MainWindow", "Hide Greenscreen"))
        self.spinBoxCam.setToolTip(_translate("MainWindow", "Select the camera index. You might wanna leave this alone."))
        self.groupBox.setTitle(_translate("MainWindow", "Noise Removal"))
        self.comboBoxNoise.setToolTip(_translate("MainWindow", "The type of noise removal. This changes the shape of the noise filter."))
        self.comboBoxNoise.setItemText(0, _translate("MainWindow", "Circle"))
        self.comboBoxNoise.setItemText(1, _translate("MainWindow", "Cross"))
        self.comboBoxNoise.setItemText(2, _translate("MainWindow", "Rectangle"))
        self.labelSize.setText(_translate("MainWindow", "30"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Threshold"))
        self.labelThresh.setText(_translate("MainWindow", "30"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Color"))
        self.label_3.setText(_translate("MainWindow", "R:"))
        self.label_4.setText(_translate("MainWindow", "G:"))
        self.label_5.setText(_translate("MainWindow", "B:"))

